### PR TITLE
Ballon Game added

### PR DESCRIPTION
**Pull request by ahsan2002**
# Description

I have added a Simple Ballon Popping Game that is made using HTML,CSS and JS.

Kindly review and merge it.

# Checklist:

- [x] I have made this from my own
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] Are you hacktoberfest contributor?

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

https://ballongame1.netlify.app/

### CODE REVIEW

**Comment by ahsan2002** [comment]
Please review this PR.

**Comment by ahsan2002** [comment]
@amelia2802 @Sulagna-Dutta-Roy could you please review this PR!

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Comment by ahsan2002** [comment]
Please also merge this.

**Review by amelia2802 — APPROVED** [review]
Thank you for contributing 🎉 Happy Coding 🥳

**Pull request merged**
