### PR TITLE
Flower using HTML and CSS

### PR DESCRIPTION
**Pull request by ojasaklechayt**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes:  #481 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Are you hacktoberfest contributor?

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Comment by ojasaklechayt** [comment]
@Sulagna-Dutta-Roy can you please check it.

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Format: Design-Effects/Flower Design/your codes. 
Please add this in format.
This project will be in the design-Effects folder.

**Comment by ojasaklechayt** [comment]
> Format: Design-Effects/Flower Design/your codes. Please add this in format. This project will be in the design-Effects folder.

Done ma'am

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
No changes.
You've changed the PR title why??

**Comment by Sulagna-Dutta-Roy** [comment]
Nope you've not changed your folder name. I've already mentioned above

**Comment by ojasaklechayt** [comment]
> Nope you've not changed your folder name. I've already mentioned above

Is it not ? I will try once again

**Comment by ojasaklechayt** [comment]
> Nope you've not changed your folder name. I've already mentioned this above
Hi @Sulagna-Dutta-Roy 
I have made changes.
First I deleted my code from the HTML+CSS folder
Then I uploaded my code in design-effects code.
Since I had already made a pr. It automatically got updated.
Is it the correct way ?

**Comment by Sulagna-Dutta-Roy** [comment]
You've added in the correct folder but 
I told you to change that "Flower Design using Html and Css" I guess this isn't the correct folder name.
That's why I mentioned twice to change it

**Comment by ojasaklechayt** [comment]
> You've added in the correct folder but I told you to change that "Flower Design using Html and Css" I guess this isn't the correct format of folder name. That's why I mentioned twice to change it

Yep! Changed the name of the folder to "Flower Design".

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Pull request merged**
