### PR TITLE
Added Jumping Animation Folder

### PR DESCRIPTION
**Pull request by SattyamSamania**
# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Jumping

### CODE REVIEW

**Review by amelia2802 — CHANGES_REQUESTED** [review]
Move the jumping animation folder into the Css animation folder

**Comment by SattyamSamania** [comment]
> Move the jumping animation folder into the Css animation folder

Added Jumping Animation folder into CSS Animation Folder. Thank you for the correction

**Review by amelia2802 — APPROVED** [review]
Thank you for contributing to #WeBeginners-Community🥳. If you like this give it a Star ✨.
Happy Coding 👩‍💻

**Comment by SattyamSamania** [comment]
> Thank you for contributing to #WeBeginners-Community🥳. If you like this give it a Star ✨. Happy Coding 👩‍💻

Thank you for this Awesome Beginner Friendly Repository to contribute.

**Pull request merged**
