### PR TITLE
Zomato UI Clone using HTML CSS

### PR DESCRIPTION
**Pull request by vikastripathi707**
# Description

Fixes:  #590 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [ ] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Are you hacktoberfest contributor?

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
image

image

image
image

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Please do the changes:
Css Clones/Zomato Clone/your codes

**Comment by vikastripathi707** [comment]
> Please do the changes: Css Clones/Zomato Clone/your codes

Done !! Pls Merge it.

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Kindlt change your folder name:
CSS Clones/Zomato Clone/your codes

**Comment by vikastripathi707** [comment]
> Kindlt change your folder name: CSS Clones/Zomato Clone/your codes

The folder Name Changed .. ThankYou you For Guiding Me.

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Pull request merged**
