### PR TITLE
Add Water Wave Text Animation using CSS

### PR DESCRIPTION
**Pull request by purna135**
Fixes:  #275 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Are you hacktoberfest contributor?

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Water Wave Text Animation

### CODE REVIEW

**Comment by sudarsan2k5** [comment]
@amelia2802 could you please have a look on this PR?

**Comment by purna135** [comment]
Hi @amelia2802 @Sulagna-Dutta-Roy 
could you please review this PR

**Comment by Sulagna-Dutta-Roy** [comment]
Already merged this PR. Kindly open another pr for this.

**Comment by purna135** [comment]
This PR is still showing Open for me, I guess another PR that linked to this is merged but this is not.

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Pull request merged**
