### PR TITLE
Parallax background

### PR DESCRIPTION
**Pull request by Vatsalmadhur**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes:  #(issue no.)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Are you hacktoberfest contributor?

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Designs-Effects/Parallax Background/your codes
Follow the format above.
What is issue no? Mention it kindly

**Comment by Vatsalmadhur** [comment]
Issue No- #366

**Comment by Sulagna-Dutta-Roy** [comment]
Any update? You've not added this into the folder

**Comment by Sulagna-Dutta-Roy** [comment]
Still you didn't made the changes

**Comment by Sulagna-Dutta-Roy** [comment]
This project should be in designs-effects folder that I made already

**Review by Vatsalmadhur — COMMENTED** [review]
issue #366, moved files into DesignsEffects folder

**Pull request closed without merging**
