### PR TITLE
Adding yoghurt website

### PR DESCRIPTION
**Pull request by surbhi400**
# Description
It is a single page website using HTML,CSS and JS.

Fixes:  #463 

# Checklist:

- [x] I have made this from my own
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Screenshot_20230201_173311

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Html+CSS/Yogurt Page/your code

**Comment by surbhi400** [comment]
> Html+CSS/Yogurt Page/your code

I am actually unable to understand the changes you are asking for. could you please elaborate a little.

**Comment by Sulagna-Dutta-Roy** [comment]
I've mentioned the format of the PR. 
The folder name should be in cap mode. 
Html+Css/Yogurt Page/your codes

**Comment by surbhi400** [comment]
@Sulagna-Dutta-Roy please review it. I made the changes you asked for.

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Pull request merged**
