### PR TITLE
Added a registration form

### PR DESCRIPTION
**Pull request by its-me-abhishek**
- Generic registration form for library registration

# Description

Made a generic registration form for a library.

Fixes:  #458

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] Are you SWOC'23 contributor?

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Screenshot_20230128_140811

### CODE REVIEW

**Comment by its-me-abhishek** [comment]
Screenshot_20230128_140811

**Comment by its-me-abhishek** [comment]
> * Generic registration form for library registration
> 
> # Description
> Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
> 
> Fixes: #(issue no.)
> 
> ## Type of change
> * [ ]  Bug fix (non-breaking change which fixes an issue)
> * [ ]  New feature (non-breaking change which adds functionality)
> * [ ]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
> * [ ]  This change requires a documentation update
> 
> # Checklist:
> * [x]  I have made this from my own
> * [ ]  I have taken help from some online resourses
> * [ ]  My code follows the style guidelines of this project
> * [ ]  I have performed a self-review of my own code
> * [ ]  I have commented my code, particularly in hard-to-understand areas
> * [ ]  I have made corresponding changes to the documentation
> * [ ]  My changes generate no new warnings
> * [ ]  Are you hacktoberfest contributor?
> 
> # ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
kindly mention the Issue no in the PR template

**Comment by its-me-abhishek** [comment]
I have now added the issue number #458 in the template

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Pull request merged**
