### PR TITLE
Sticky cards 

### PR DESCRIPTION
**Pull request by shubham0730**
# Description
I have created a sticky cards design effect. The cards stack on each other when you scroll.
The tech stack I have used is purely html and css.

Fixes:  #491 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] Are you hacktoberfest contributor?

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
sc1
sc2

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
format: HTML+CSS/Sticky Cards/your codes

**Comment by shubham0730** [comment]
?

**Comment by Sulagna-Dutta-Roy** [comment]
Change the folder name as per above Instruction

**Comment by shubham0730** [comment]
Done

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Pull request merged**
