### PR TITLE
JavaScript form validation

### PR DESCRIPTION
**Pull request by Deep0123**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes:  #(issue no.)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [ ] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] My changes generate no new warnings
- [x] I'm hacktoberfest contributor

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Add this project into Forms folder.

**Comment by Deep0123** [comment]
done

**Review by Sulagna-Dutta-Roy — APPROVED** [review]
Great project. Thanks for contributing here

**Comment by Deep0123** [comment]
Thank you very much mam🥰

**Pull request merged**
