### PR TITLE
Hover Icon

### PR DESCRIPTION
**Pull request by Mridul-2003**
# Description

I have made animated Hover icon images .

Fixes:  #384 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Are you hacktoberfest contributor?

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Screenshot 2023-03-07 at 6 19 32 PM

### CODE REVIEW

**Comment by Mridul-2003** [comment]
plz merge this pull request

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Css Animations/Hover Icons/your codes

**Comment by Mridul-2003** [comment]
Screenshot_2023-03-08-09-42-13-896_com android chrome
I have already done,  so what can I do 
Plz check it carefully.

**Comment by Sulagna-Dutta-Roy** [comment]
Change the folder name that you created

**Pull request closed without merging**
