### PR TITLE
Add Newton's Cradle Animation using CSS

### PR DESCRIPTION
**Pull request by purna135**
Fixes:  #279 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Are you hacktoberfest contributor?

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Newton's Cradle Animation

### CODE REVIEW

**Comment by sudarsan2k5** [comment]
@amelia2802 could you please have a look on this PR?

**Comment by purna135** [comment]
Hi @Sulagna-Dutta-Roy could you please have a look at this PR

**Comment by Sulagna-Dutta-Roy** [comment]
Because you've added another project in this Pr. Kindly make Pull requests one by one.

**Comment by purna135** [comment]
I have only one Project added in this particular PR

**Comment by purna135** [comment]
I have created 3 different PR for 3 different projects separately

**Pull request merged**
