### PR TITLE
New commit INSTAGRAM CLONE

### PR DESCRIPTION
**Pull request by Bishal011**
of issue Title: Instagram clone  #498

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes:  #498 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

Screenshot (206)

### CODE REVIEW

**Comment by Bishal011** [comment]
Plz review this issue

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Css Clones/Instgram Clone/your codes
Kindly do the changes above

**Comment by Bishal011** [comment]
Done the changes
Please now review it

**Comment by Sulagna-Dutta-Roy** [comment]
I can see 51+ files here 
Code is not rightly pushed

**Pull request closed without merging**
