### PR TITLE
Transparent Navbar

### PR DESCRIPTION
**Pull request by Tasmiya-k**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes:  #12 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
image

### CODE REVIEW

**Comment by Tasmiya-k** [comment]
@Sulagna-Dutta-Roy pls review

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Add this project into Navbar folder and make the project folder as 'Transparent Folder'

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Review by amelia2802 — CHANGES_REQUESTED** [review]
Hey @Tasmiya-k , your navbar looks good and the color contrast is also great. But can you make the navbar a bit responsive for mobile? the work & contact are misplaced.
mobile preview

**Comment by Tasmiya-k** [comment]
Yes I will do the changes

**Comment by Tasmiya-k** [comment]
@amelia2802 pls review

**Comment by Tasmiya-k** [comment]
@Sulagna-Dutta-Roy pls review

**Review by amelia2802 — APPROVED** [review]

**Pull request merged**
