### PR TITLE
Added form wave animation

### PR DESCRIPTION
**Pull request by sanil011**
# Description

Added a css form wave which can be used by anyone for their projects ,took inspiration from the css tricks website for the above component

Fixes:  #(89)

## Type of change

- [✅  ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [✅  ] I have made this from my own
- [ ✅ ] I have taken help from some online resourses 
- [ ✅ ] My code follows the style guidelines of this project
- [ ✅ ] I have performed a self-review of my own code
- [ ✅ ] I have commented my code, particularly in hard-to-understand areas
- [✅  ] I have made corresponding changes to the documentation
- [ ✅ ] My changes generate no new warnings
- [ ✅ ] Are you hacktoberfest contributor?

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

https://user-images.githubusercontent.com/105095685/194805954-a99817fb-b611-41e1-8e13-76b15028b301.mov

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
.ds_store should be deleted.
Please make one pull request other should be closed

**Comment by sanil011** [comment]
.ds_store is deleted
I will close another pull request .

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Comment by Sulagna-Dutta-Roy** [comment]
Theme clock pull request is still showing here. Please close it

**Comment by sanil011** [comment]
> Theme clock pull request is still showing here. Please close it

now deleted

**Pull request merged**
