### PR TITLE
added a project

### PR DESCRIPTION
**Pull request by sumitkr2000**
# Description

I added a front-end project to this repository.

Fixes:  #(issue no.)

308

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] Are you hacktoberfest contributor?

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
https://cozy-sable-37d695.netlify.app/

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Submodules should not be pushing here.Kindly look into it

**Comment by sumitkr2000** [comment]
@sulakshanachetry sorry i didn't understand

**Comment by sumitkr2000** [comment]
@Sulagna-Dutta-Roy What did u say?

**Comment by Sulagna-Dutta-Roy** [comment]
> @Sulagna-Dutta-Roy What did u say?

You have pushed submodules files that should not be accepted. Kindly check others PRs

**Comment by sumitkr2000** [comment]
Now check @Sulagna-Dutta-Roy

**Comment by sumitkr2000** [comment]
merge my pr @Sulagna-Dutta-Roy

**Comment by sumitkr2000** [comment]
merge my pr @Sulagna-Dutta-Roy

**Comment by sumitkr2000** [comment]
merge my pr @Sulagna-Dutta-Roy

**Comment by Sulagna-Dutta-Roy** [comment]
It's same thing showing. Kindly close this PR and close it

**Comment by sumitkr2000** [comment]
ok I will create a new pr

**Pull request closed without merging**
