### PR TITLE
Hover Card

### PR DESCRIPTION
**Pull request by vimarsh11**
# Description
I have created Hover Card using HTML, CSS.

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes:  #363

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Checklist:

- [x
Screenshot 2023-01-25 121256
Screenshot 2023-01-25 121332
] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Are you hacktoberfest contributor?

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Format: Css Animations/Hover Card/your codes

**Comment by Sulagna-Dutta-Roy** [comment]
It's showing the same. Mentioned the format above kindly do it

**Comment by vimarsh11** [comment]
> It's showing the same. Mentioned the format above kindly do it

@Sulagna-Dutta-Roy done!

**Review by Sulagna-Dutta-Roy — APPROVED** [review]
Perfect

**Pull request merged**
