### PR TITLE
feat-Flat Booking System

### PR DESCRIPTION
**Pull request by BotSonu**
Landing Page using HTML + CSS
Fixes: #435

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Are you hacktoberfest contributor?

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Link- http://127.0.0.1:5500/Index.html

SS-1
SS-2
SS-3

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Make one folder Images and attach all the Images there.
Format:HTML+CSS/Landing Page/ Images/ your image files.
change the folder name mentioned

**Comment by BotSonu** [comment]
Is it ok now?

**Comment by Sulagna-Dutta-Roy** [comment]
Told you to change the folder name and remove the punctuation.
Landing Page only

**Comment by BotSonu** [comment]
please check this

**Comment by Sulagna-Dutta-Roy** [comment]
I told you to make Image folder for all the Images.

**Comment by BotSonu** [comment]
done

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Your codes will be storing only in Landing pages folder. 
I can see lots of images out of the folder. Hence you need to see other successful PRs

**Comment by BotSonu** [comment]
IMG_20230203_020448

**Pull request closed without merging**
