### PR TITLE
Personal Portfolio Website Added

### PR DESCRIPTION
**Pull request by iamwicked**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes:  #(issue no.)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Are you hacktoberfest contributor?

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Comment by iamwicked** [comment]
This pull request resolves issue #243

**Review by amelia2802 — CHANGES_REQUESTED** [review]
Remove the.DS store. And try to link other hypertext references before your main css.

**Comment by iamwicked** [comment]
could you please elaborate what do you mean by link other href before main css

**Comment by iamwicked** [comment]
Thank you for the valuable feedback. Please review the changes made.

**Review by amelia2802 — APPROVED** [review]
Thank you for contributing 🎉 Happy Coding 🥳

**Pull request merged**
