### PR TITLE
Added Responsive Light/Dark Themed Navigation Bar

### PR DESCRIPTION
**Pull request by AmitSahoo45**
# Description

This is an addition to a responsive navigation menu made using HTML, CSS, and JavaScript.

Fixes:  #(issue no.)

#330 

This targets fixing Issue No. 330

## Type of change

- [x ] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

image
image
image

### CODE REVIEW

**Comment by Sulagna-Dutta-Roy** [comment]
this code is not rightly pushed.

**Comment by AmitSahoo45** [comment]
Not rightly pushed??? like I don't get it???

**Comment by AmitSahoo45** [comment]
But I haven't made any changes to the **Floating Label Text Input/index.css** file. It's just the same.

**Comment by Sulagna-Dutta-Roy** [comment]
One thing you do this close this PR. 
Delete the fork then make new PR again. Only issue no will be the same

**Pull request closed without merging**
