### PR TITLE
Hover Card

### PR DESCRIPTION
**Pull request by vimarsh11**
# Description

I have created an Hover Card using HTML, CSS.

Fixes:  #363 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Are you hacktoberfest contributor?

# ATTACH SCREEN-SHOTS / DEPL
Screenshot 2023-01-25 121256
Screenshot 2023-01-25 121332
OYMENT LINK

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Two PRs showing in the same branch. For this one flipcard is showing??

**Comment by vimarsh11** [comment]
> Two PRs showing in the same branch. For this one flipcard is showing??

I have deleted that file now check it.

**Comment by Sulagna-Dutta-Roy** [comment]
Add this project to Css animations folder.

**Comment by Sulagna-Dutta-Roy** [comment]
Make the above changes

**Pull request closed without merging**
