### PR TITLE
Tetris Game

### LINKED ISSUE #449: Tetris Game
# Description

Tetris is a puzzle video game.In Tetris, players complete lines by moving differently shaped pieces ([tetrominoes]), which descend onto the playing field.

### PR DESCRIPTION
**Pull request by S-ishita**
Closes #449 

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

Screenshot from 2023-01-08 16-04-14
Screenshot from 2023-01-08 16-04-03
Screenshot from 2023-01-08 16-03-54

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Kindly make your folder name into 'Tetris Game'

**Comment by S-ishita** [comment]
Done @Sulagna-Dutta-Roy

**Comment by Sulagna-Dutta-Roy** [comment]
@S-ishita Please do the changes

**Comment by S-ishita** [comment]
Done @Sulagna-Dutta-Roy

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Comment by Sulagna-Dutta-Roy** [comment]
Kindly attach the Issue no in the PR template. And PR template should be same before I can see you've deleted the template

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Comment by S-ishita** [comment]
@Sulagna-Dutta-Roy kindly add the labels for this

**Pull request merged**
