### PR TITLE
Dragon Game

### PR DESCRIPTION
**Pull request by Sirsha2468**
# Description

This is a dragon game made using HTML, CSS & JS. Here JS is used most. Kindly check this out, in PC (More preffered).. Thank you. 

Fixes:  #(issue no.)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Are you hacktoberfest contributor?

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
https://sirsha2468.github.io/Dragon-game
image
image

### CODE REVIEW

**Comment by Sirsha2468** [comment]
Can you please tell me what is the problem with this or what I have to add or change or whether I have made any mistakes?

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Add this projecy into Css-games folder

**Comment by Sulagna-Dutta-Roy** [comment]
> Can you please tell me what is the problem with this or what I have to add or change or whether I have made any mistakes?

Already told you kindly do the needful

**Comment by Sirsha2468** [comment]
I did that. It is now added in GAMES folder

**Comment by Sirsha2468** [comment]
Please 🙏 🥺 tell me is not it added on the games folder?

**Comment by Sulagna-Dutta-Roy** [comment]
I didn't find any project folder name like "Dragon Game" You've added directly into the games folder. 
Please check other games project.

**Comment by Sirsha2468** [comment]
> I didn't find any project folder name like "Dragon Game" You've added directly into the games folder. 
> Please check other games project. 

Okay, then I am creating a folder name - JS games, under that I will be adding my project. Is that okay 👍 with you?

**Comment by Sulagna-Dutta-Roy** [comment]
I've already made one folder named 'Games' . You need to make 'Dragon Game' folder under this 'Games' folder. Why don't you check the other games PR. I've already written all the guidelines.

**Comment by Sirsha2468** [comment]
> I've already made one folder named 'Games' . You need to make 'Dragon Game' folder under this 'Games' folder. Why don't you check the other games PR. I've already written all the guidelines.

Done. Added now, please accept the pull request, and merged it for the hactoberfest 2022

**Comment by Sulagna-Dutta-Roy** [comment]
No done again. I can't see any deagon game folder under games folder. Kindly check other games

**Comment by Sirsha2468** [comment]
> No done again. I can't see any deagon game folder under games folder. Kindly check other games

I don't really no what's the issue, 😆 . And I see there is a review left, please take a look.

**Pull request closed without merging**
