### PR TITLE
Added spiderman

### PR DESCRIPTION
**Pull request by sumitkr2000**
# Description

Hey, @Sulagna-Dutta-Roy I have added the spiderman project. Please review my pr and merge it. Thank you!

Fixes:  #(issue no.)

#619 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] Are you hacktoberfest contributor?

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Screenshot (664)

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Move this project to design-effects

**Comment by sumitkr2000** [comment]
done @Sulagna-Dutta-Roy .

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Designs-Effects/SpiderMan Effect/your codes

**Comment by sumitkr2000** [comment]
Done now please check @Sulagna-Dutta-Roy

**Pull request merged**
