### PR TITLE
Animated photo gallery

### PR DESCRIPTION
**Pull request by shubham0730**
# Description

I have created an animated photo gallery.
The tech stack I have used is purely html and css

Fixes:  #316

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] Are you hacktoberfest contributor?

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

gallery

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
This project should be add in Css Animations folder.
Make one folder called Images and add all pexels into it.
Project folder name should be: Css Animations/Photo Gallery

**Comment by shubham0730** [comment]
Have made the necessary changes

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Comment by Sulagna-Dutta-Roy** [comment]
Please attach the Issue no n the PR template

**Comment by shubham0730** [comment]
Done

**Pull request merged**
