### PR TITLE
Hover icon

### PR DESCRIPTION
**Pull request by Mridul-2003**
# Description

I have added a file ,
For hovering icon using html and css .

- [yes ] Are you hacktoberfest contributor?

Screenshot 2023-01-17 at 4 40 37 PM

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Comment by Mridul-2003** [comment]
Plz merge this pull

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Please add this project to:
Css Animations/ Hover Icons/your codes

**Review by Mridul-2003 — COMMENTED** [review]
I have made the requested changes plz review and merge the PR

**Comment by Sulagna-Dutta-Roy** [comment]
I can't see the changes

**Comment by Mridul-2003** [comment]
I have made the requested changes plz check the commits .

**Comment by Mridul-2003** [comment]
Screenshot 2023-03-07 at 6 13 28 PM
plz check the latest commit.

**Pull request closed without merging**
