### PR TITLE
Deleting the directory

### PR DESCRIPTION
**Pull request by aryaman1202**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Would like to delete this directory of the repository as some error in the folder is causing a lot of problem and the particular repository is not getting cloned. Please accept this request as I am not able to clone the repo and can't further contribute to the project repo. @Sulagna-Dutta-Roy

Fixes:  #(issue no.)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

photoo

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Comment by Sulagna-Dutta-Roy** [comment]
I've deleted this directory for the errors for everyone who are facing.
And now everyone able to push their codes through git.
Kindly check your system too

**Comment by aryaman1202** [comment]
> I've deleted this directory for the errors for everyone who are facing. And now everyone able to push their codes through git. Kindly check your system too

Ma'am I am not able to see any changes and the directory still exists. Please suggest @Sulagna-Dutta-Roy

**Comment by Sulagna-Dutta-Roy** [comment]
Update your fork then.
Because other are clearly making PRs without any conflicts.
If I merge it then others will facing the problem

**Comment by Sulagna-Dutta-Roy** [comment]
You can see the original repo

**Pull request closed without merging**
