### PR TITLE
feat-40-various_states_of_cursors

### PR DESCRIPTION
**Pull request by its-harsshhh**
# Description

The style of Cursor changes when we hover on different buttons

for example : if we hover mouse cursor on "wait button", the cursor changes to "loading" state of cursor

Fixes:  #40

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [ ] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Are you hacktoberfest contributor?

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
css cursors

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
CSS_of_Cursors change into 'CSS Cursors ' only

**Comment by its-harsshhh** [comment]
@Sulagna-Dutta-Roy what and where i have to change?

**Comment by its-harsshhh** [comment]
Do you mean, i have to change the folder name?

**Comment by its-harsshhh** [comment]
And kindly please put hacktoberfest label on the issue

**Pull request closed without merging**
