### PR TITLE
feat-Flat Booking System

### PR DESCRIPTION
**Pull request by BotSonu**
# Description

Landing Page using HTML + CSS
Fixes: #435 

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] Are you hacktoberfest contributor?

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

Link- http://127.0.0.1:5500/Index.html

SS-1

SS-2

SS-3

Please consider this file.

### CODE REVIEW

**Comment by BotSonu** [comment]
Please respond for this PR

**Comment by Sulagna-Dutta-Roy** [comment]
I can't see the Issue no here.

**Comment by BotSonu** [comment]
Actually this is not any issue. I have created a random project ( landing Page) own

**Comment by Sulagna-Dutta-Roy** [comment]
But the guidelines for every PRs is same for all. Issue means the main part of the raising PR.
Kindly check other merged PRs.

**Comment by BotSonu** [comment]
I have updated it .

**Comment by Sulagna-Dutta-Roy** [comment]
@botsonu again you've attached the PR no in the PR template. 
I told you to add Issue no there #331 is the PR no. 
Otherwise this PR will be rejected

**Comment by BotSonu** [comment]
Ok ok  got it. Thank you.

**Comment by Sulagna-Dutta-Roy** [comment]
Please add this project in the Html+Css folder along with your project folder.
Check another successful PRs format that I've merged

**Pull request closed without merging**
