### PR TITLE
Added a CSS toggle button

### PR DESCRIPTION
**Pull request by vandana3869**
# Description
Created a folder and  added a CSS toggle button with day-night design

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Are you hacktoberfest contributor?

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
image
image

### CODE REVIEW

**Comment by vandana3869** [comment]
@Sulagna-Dutta-Roy  could u please review this code

**Comment by vandana3869** [comment]
@Sulagna-Dutta-Roy I already made the changes ..could you please review this PR

**Comment by vandana3869** [comment]
@amelia2802  @Sulagna-Dutta-Roy  could you please review this PR

**Comment by amelia2802** [comment]
@vandana3869 your PR has merge conflict. To resolve this issue create two separate pull request. One for toggle and another for animation

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Please update the forked repo and branch. It's showing conflicts

**Pull request closed without merging**
