### PR TITLE
Parallax scroll

### PR DESCRIPTION
**Pull request by Vatsalmadhur**
# A parallax scrolling background

made this awsome parallax scrolling background.

Fixes:  #366 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Are you hacktoberfest contributor?

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
https://vatsalmadhur.github.io/CSS.Effects-Designs/

### CODE REVIEW

**Comment by Vatsalmadhur** [comment]
Completed,please review

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Please delete the .ds store files that not needed

**Comment by Vatsalmadhur** [comment]
Deleted the .ds store files.

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Still showing two ds store files

**Pull request closed without merging**
